name: Years of Lead CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: years_of_lead_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/years_of_lead_test
        MONGODB_URL: mongodb://localhost:27017
        JWT_SECRET_KEY: test_secret_key_for_ci_environment
      run: |
        pytest src/tests/ --cov=src

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build API Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: years-of-lead-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build UI Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./src/ui
        push: false
        tags: years-of-lead-ui:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Uncomment when ready for deployment
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Deploy to development environment
  #     run: echo "Add deployment steps here"
